whitelist_rules:
- colon
- comma
- control_statement
- file_length
- force_cast
- force_try
- function_body_length
- leading_whitespace
- nesting
- opening_brace
- operator_whitespace
- return_arrow_whitespace
- statement_position
- todo
- trailing_newline
- trailing_semicolon
- trailing_whitespace
- type_body_length
- type_name
- variable_name_max_length
- variable_name_min_length
- variable_name
disabled_rules: # rule identifiers to exclude from running
#  - colon
#  - comma
#  - control_statement
#  - file_length
#  - force_cast
#  - force_try
#  - function_body_length
#  - leading_whitespace
#  - nesting
#  - opening_brace
#  - operator_whitespace
#  - return_arrow_whitespace
#  - statement_position
#  - todo
#  - trailing_newline
#  - trailing_semicolon
#  - trailing_whitespace
#  - type_body_length
#  - type_name
#  - variable_name_max_length
#  - variable_name_min_length
#  - variable_name
included: # paths to include during linting. `--path` is ignored if present. takes precendence over `excluded`.
   - Learnwise
#  - LearnwiseTests
excluded: # paths to ignore during linting. overridden by `included`.
  - Pods
#  - LearnwiseTests
file_length:
  warning: 500
  error: 1200
function_body_length:
#  - 75
#  - 100
type_body_length:
  - 300 # Warning
  - 400 # Error
line_length:
   - 120
